services:
  - type: web
    name: n8n
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    envVars:
      - key: DB_TYPE
        value: postgresdb
      # ... Postgres creds via linked database
      - key: N8N_BASIC_AUTH_ACTIVE
      # other ENV vars ...
      - key: WEBHOOK_URL
        value: https://n8n.onrender.com

databases:
  - name: n8n-db
    plan: free
    region: oregon
